import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1750988916954 implements MigrationInterface {
    name = 'Migration1750988916954'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "VideoMetadata" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "autoGeneratedDescription" text, "transcript" text NOT NULL, "ageRating" integer, "ageRatingExplanation" text, "ageRatingCategories" text array, "videoId" uuid, CONSTRAINT "REL_678d67fbd94f3a4f4c57a0507b" UNIQUE ("videoId"), CONSTRAINT "PK_67db734088f52ed6ffea3346abf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "VideoMetadata" ADD CONSTRAINT "FK_678d67fbd94f3a4f4c57a0507b0" FOREIGN KEY ("videoId") REFERENCES "Video"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "VideoMetadata" DROP CONSTRAINT "FK_678d67fbd94f3a4f4c57a0507b0"`);
        await queryRunner.query(`DROP TABLE "VideoMetadata"`);
    }

}
