import { contentFactory } from '@contentModule/__test__/factory/content.factory'
import { movieFactory } from '@contentModule/__test__/factory/movie.factory'
import { videoMetadataFactory } from '@contentModule/__test__/factory/video-metadata.factory'
import { videoFactory } from '@contentModule/__test__/factory/video.factory'
import { CONTENT_TEST_FIXTURES } from '@contentModule/__test__/test.constant'
import { Video } from '@contentModule/shared/persistence/entity/video.entity'
import { ContentVideoProcessorModule } from '@contentModule/video-processor/content-video-processor.module'
import { GenerateSummaryForVideoUseCase } from '@contentModule/video-processor/core/use-case/generate-summary-for-video.use-case'
import { INestApplication } from '@nestjs/common'
import { TestingModule } from '@nestjs/testing'
import { Tables } from '@testInfra/enum/table.enum'
import { testDbClient } from '@testInfra/knex.database'
import { createNestApp } from '@testInfra/test-e2e.setup'
import nock, { cleanAll } from 'nock'

describe('GenerateSummaryForVideoUseCase', () => {
  let module: TestingModule
  let app: INestApplication
  let generateSummaryForVideoUseCase: GenerateSummaryForVideoUseCase

  beforeAll(async () => {
    const nestTestSetup = await createNestApp([ContentVideoProcessorModule])
    app = nestTestSetup.app
    module = nestTestSetup.module
    generateSummaryForVideoUseCase = module.get<GenerateSummaryForVideoUseCase>(
      GenerateSummaryForVideoUseCase
    )
  })

  afterEach(async () => {
    await testDbClient(Tables.VideoMetadata).del()

    await testDbClient(Tables.Video).del()
    await testDbClient(Tables.Movie).del()
    await testDbClient(Tables.Thumbnail).del()
    await testDbClient(Tables.Content).del()

    cleanAll()
    jest.restoreAllMocks()
  })

  afterAll(async () => {
    await app.close()
    await module.close()
  })

  it('generates a summary for a video with existing metadata', async () => {
    const content = contentFactory.build()
    const movie = movieFactory.build({
      contentId: content.id
    })
    const video = videoFactory.build({
      url: `${CONTENT_TEST_FIXTURES}/sample.mp4`,
      movieId: movie.id
    })
    const videoMetadata = videoMetadataFactory.build({
      videoId: video.id
    })
    await testDbClient('Content').insert(content)
    await testDbClient('Movie').insert(movie)
    await testDbClient('Video').insert(video)
    await testDbClient('VideoMetadata').insert(videoMetadata)

    nock('https://generativelanguage.googleapis.com')
      .post('/v1beta/models/gemini-2.0-flash:generateContent')
      .query(true) // Match any query parameters
      .reply(200, {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: JSON.stringify({
                    responseText: 'This is a test video summary.'
                  })
                }
              ]
            },
            finishReason: 'STOP',
            index: 0
          }
        ]
      })

    const videoEntity = new Video(video)

    await generateSummaryForVideoUseCase.execute(videoEntity)
    const updatedVideoMetadata = await testDbClient('VideoMetadata')
      .where({ videoId: video.id })
      .first()
    expect(updatedVideoMetadata).toBeDefined()
    expect(updatedVideoMetadata.autoGeneratedDescription).toEqual(
      'This is a test video summary.'
    )
  })

  it('creates new metadata when no metadata exists for the video', async () => {
    // Create content without metadata
    const content = contentFactory.build()
    const movie = movieFactory.build({
      contentId: content.id
    })
    const video = videoFactory.build({
      url: `${CONTENT_TEST_FIXTURES}/sample.mp4`,
      movieId: movie.id
    })
    await testDbClient('Content').insert(content)
    await testDbClient('Movie').insert(movie)
    await testDbClient('Video').insert(video)

    nock('https://generativelanguage.googleapis.com')
      .post('/v1beta/models/gemini-2.0-flash:generateContent')
      .query(true)
      .reply(200, {
        candidates: [
          {
            content: {
              parts: [
                {
                  text: JSON.stringify({
                    responseText:
                      'New video summary for content without metadata.'
                  })
                }
              ]
            },
            finishReason: 'STOP',
            index: 0
          }
        ]
      })

    const videoEntity = new Video(video)

    await generateSummaryForVideoUseCase.execute(videoEntity)

    // Verify a new metadata record was created
    const newMetadata = await testDbClient('VideoMetadata')
      .where({ videoId: video.id })
      .first()

    expect(newMetadata).toBeDefined()
    expect(newMetadata.autoGeneratedDescription).toEqual(
      'New video summary for content without metadata.'
    )
  })

  it('handles API errors during summary generation', async () => {
    const content = contentFactory.build()
    const movie = movieFactory.build({
      contentId: content.id
    })
    const video = videoFactory.build({
      url: `${CONTENT_TEST_FIXTURES}/sample.mp4`,
      movieId: movie.id
    })
    await testDbClient('Content').insert(content)
    await testDbClient('Movie').insert(movie)
    await testDbClient('Video').insert(video)

    // Mock the API to throw an error
    nock('https://generativelanguage.googleapis.com')
      .post('/v1beta/models/gemini-2.0-flash:generateContent')
      .query(true)
      .replyWithError('API connection error')

    const videoEntity = new Video(video)

    await expect(
      generateSummaryForVideoUseCase.execute(videoEntity)
    ).rejects.toThrow()
  })
})
