import { VideoMetadata } from '@contentModule/shared/persistence/entity/video-metadata.entity'
import { faker } from '@faker-js/faker/.'

import * as Factory from 'factory.ts'

export const videoMetadataFactory = Factory.Sync.makeFactory<
  Partial<VideoMetadata>
>({
  id: faker.string.uuid(),
  autoGeneratedDescription: faker.lorem.paragraph(),
  transcript: faker.lorem.paragraph(),
  ageRating: faker.number.int({ min: 0, max: 18 }),
  ageRatingExplanation: faker.lorem.sentence(),
  ageRatingCategories: faker.helpers.arrayElements(
    ['Violence', 'Language', 'Sexual Content'],
    3
  ),
  version: 1,
  videoId: faker.string.uuid(),
  createdAt: faker.date.recent(),
  updatedAt: faker.date.recent(),
  deletedAt: null
})
